### ISSUE TITLE
DIY branch coverage

### ISSUE THREAD

**Issue by luminiusa** [luminiusa/geometry-api-java#2]

**Comment by jvgille** [comment]
I am going to instrument the following methods. They all have CCN over 15 and have branch coverage which could be improved.
`MultiPathImpl::addSegmentsFromPath@697-822`
`MultiPathImpl::insertPoints@1079-1185`
`TopologicalOperations::normalizeResult_@1525-1573`
`AttributeStreamOfInt16::writeRange@470-523`
`MultiPathImpl::openAllPathsAndDuplicateStartVertex@382-457`
`RasterizedGeometry2DImpl::queryEnvelopeInGeometry@434-489`
`OperatorExportToGeoJsonCursor::exportPolygonToGeoJson_@178-234`
`SweepComparator::compareSegments@599-656`
`OperatorImportFromWkbLocal::importFromWkbMultiPoint@906-1009`
`RelationalOperationsMatrix::areaGeomContainsOrDisjointPredicates_@1704-1730`

**Comment by jvgille** [comment]
Maven normally surpresses test output, so to be able to see the output from the manual coverage tool you can run the tests using `mvn -Dmaven.junit.usefile=false test`
