### ISSUE TITLE
Identify/Document 10 methods with high complexity

### ISSUE THREAD

**Issue by GriesserP** [luminiusa/geometry-api-java#4]
We have to identify 10 methods and document the purpose of them, and why the complexity should be high (or not)

**Comment by GriesserP** [comment]
Already taken:
the **flatten** method from 
src/main/java/com/esri/core/geometry/ogc/OGCConcreteGeometryCollection.java
the **writeRange** method from
src/main/java/com/esri/core/geometry/AttributeStreamOfInt16.java

**Comment by ArthurVignon** [comment]
I'm doing:
the importFromJsonParser method from
src/main/java/com/esri/core/geometry/OperatorImportFromJsonCursor.java

**Comment by GriesserP** [comment]
The ten functions have been chosen to be the 10 most complex ones according to lizard.
The comments have been done for those functions.
